Disable all calls for migration
integritee-network/integritee-node pull request #118
Opened 2022-04-06 11:30 UTC by echevrier

Disable all calls for migration
Bump version: spec version = 9

2022-04-06 12:33 UTC, echevrier commented
Runtime upgrade tested. After the runtime upgrade, transfer are impossible.

2022-04-06 14:52 UTC, brenzi requested changes
If you do test again, please not only test that balance transfers are filtered, also test that sudo calls are still possible. (I have no doubt, but let's be very thorough

2022-04-06 14:52 UTC, brenzi commented on runtime/src/lib.rs
> +			Call::Vesting(_)
what about `system`? If I'm not mistaken, `system.remark()` is not privileged. We may want to filter that too

2022-04-06 15:26 UTC, echevrier commented on runtime/src/lib.rs
> +			Call::Vesting(_)
Only system call remark? If we want to make the upgrade we need the system setCode.

2022-04-06 15:50 UTC, brenzi commented on runtime/src/lib.rs
> +			Call::Vesting(_)
sudo can do all calls anyway no matter the filtering

2022-04-06 15:51 UTC, brenzi commented on runtime/src/lib.rs
> +			Call::Vesting(_)
...as long as we don't filter sudo itself ;-)

2022-04-06 15:53 UTC, brenzi commented on runtime/src/lib.rs
> +			Call::Vesting(_)
actually, last time we didn't filter system, so let's do it the same way now

2022-04-06 15:53 UTC, brenzi commented on runtime/src/lib.rs
> +			Call::Vesting(_)
https://github.com/integritee-network/integritee-node/blob/6a445c05618016cea7057fe3dbf566027f596c0a/runtime/src/lib.rs#L221-L239

2022-04-06 15:54 UTC, brenzi approved these changes

2022-04-06 15:55 UTC, brenzi requested changes
one more thing: if you bump spec version, you have to bump pallet versions too. for runtime and node

2022-04-06 15:55 UTC, echevrier commented
> If you do test again, please not only test that balance transfers are filtered, also test that sudo calls are still possible. In the best case, perform another setCode() because that's what we may need to do if things go sideways with the migration. (I have no doubt it will work, but let's be very thorough)
Sudo call are working

2022-04-06 19:04 UTC, brenzi commented
There was a misunderstanding about my comment. But it's ok like this too I think. But we need to test again if sudo setCode works to be sure

2022-04-07 06:59 UTC, haerdib approved these changes
LGTM. I was able to upgrade and downgrade the runtime again with two --dev nodes running locally.

2022-04-07 07:07 UTC, echevrier commented
> There was a misunderstanding about my comment. But it's ok like this too I think. But we need to test again if sudo setCode works to be sure

I did all tests again

2022-04-07 15:35 UTC, brenzi approved these changes

2022-04-07 15:35 UTC, merged